name: Android CI/CD Helios

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Otorgar permisos de ejecución a Gradle
      run: chmod +x gradlew

    - name: Compilar APK de Depuración (Debug)
      run: ./gradlew assembleDebug

    - name: Subir APK terminada como Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: CalcMaster-Teclado-APK
        path: app/build/outputs/apk/debug/app-debug.apk
